<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Debug Textbox</name>
   <tag></tag>
   <elementGuidId>cef39d24-c231-4ad1-be04-8cf40c0ddada</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#debugTextbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='debugTextbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>155a68fc-5e06-4833-b781-826e2c89bb42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>72e76628-c711-4a9f-a376-06a144d6f04c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>debugTextbox</value>
      <webElementGuid>d1115f0d-9979-4961-a205-1689ac7d5c89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;debugTextbox&quot;)</value>
      <webElementGuid>70aabfbb-e57b-47ff-b549-872d440be262</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='debugTextbox']</value>
      <webElementGuid>3e5b5f78-27a0-4963-9a17-acb8a5b008b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4e63cd08-97f3-48c4-a99d-8f26217b8c72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'debugTextbox']</value>
      <webElementGuid>f661e720-6b83-4fdf-bb53-77f6fc8c2764</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
